CREATE SEQUENCE seq_statie START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_tip_carburant START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_pompa START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_pistol_pompa START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_client START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_angajat START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_tura START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_bon_fiscal START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_alimentare START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_produs_magazin START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_furnizor START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_aprovizionare START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_livrare_carburant START WITH 1 INCREMENT BY 1;